Add files via upload
nithindante/Amazontesting pull request #1
Opened 2023-07-29 08:55 UTC by nithindante

2023-07-30 21:31 UTC, rgehy84 requested changes

2023-07-30 21:31 UTC, rgehy84 commented on AmazonAs.java
> +		driver.findElement(By.id("twotabsearchtextbox")).sendKeys(Keys.ARROW_DOWN);
why are you using keys here and not clicks?

2023-07-30 21:31 UTC, rgehy84 commented on AmazonAs.java
> +		driver.findElement(By.xpath("//*[@id=\"search\"]/div[1]/div[1]/div/span[1]/div[1]/div[3]/div/div/div/div/div/div/div[2]/span/a/div")).click();
this xpath is terrible, it will easily break when a slight modification is made on the site. Check out this video for choosing great, amazing, super locators
https://www.youtube.com/watch?v=9qgD2wCFOLo

Also, in the ID, if you are using double quotes to open the parameter, use single quotes so you don't have to escape the double quote.

i.e. By.xpath("//*[@id='search']")

2023-07-30 21:31 UTC, rgehy84 commented on AmazonAs.java
> +		Thread.sleep(2000);
per goodguy63 in the YouTube livestream chat, you should be using explicit wait instead of thread sleep as much as possible. You can look into doing waiting until element is clickable or visible or displayed or something like that. You have to try it out and see which works best. Look for WebDriverWaits and it will direct you in the right direction.

2023-07-30 21:31 UTC, rgehy84 commented on AmazonAs.java
> +				Thread.sleep(2000);
as above, try to implement WebDriverWait

2023-07-30 21:31 UTC, rgehy84 commented on AmazonAs.java
> +			    driver.findElement(By.xpath("//*[@id=\"address-ui-widgets-form-submit-button\"]/span/input")).click();
try to use CSS selector when possible instead of xpath. Keep xpath as your last option as CSS selectors are easier read. 
`div#address-ui-widgets-form-submit-button > span > input`

2023-07-30 21:31 UTC, rgehy84 commented on AmazonAs.java
> +			    driver.findElement(By.xpath("//*[@id=\"address-ui-widgets-form-submit-button\"]/span/input")).click();
Add an assert to validate something on the last step. That way you'll know if the test made it to the last expected page after the click. 

i.e. Validate that the complete order button is displayed

2023-07-30 21:31 UTC, rgehy84 commented on AmazonAs.java
> +	public void run() throws InterruptedException
name the method something that describes your test case
i.e. testAmazonCheckoutFlow

2023-07-30 21:31 UTC, rgehy84 commented on AmazonAs.java
> +	@Test
I would suggest adding a description to the @Test annotation like this:
@Test(description="Testing the Amazon Add Product to Cart Workflow")

2023-07-30 21:31 UTC, rgehy84 commented on AmazonAs.java
> +		driver.findElement(By.id("nav-link-accountList")).click();
For the time being, print out the steps that are being followed to the console.
`System.out.println("Click the Account List in the Navigation")`

2023-07-31 19:36 UTC, nithindante commented on AmazonAs.java
> +	public void initialise()
Sure thing,  since I was just using one test, I thought of using this, yeah its better to wrap it up under @BeforeMethod so that it is called before each test.

2023-07-31 19:43 UTC, nithindante commented on AmazonAs.java
> +	public void geturl()
I should be getting better at method and object names, I mean I am trying to, After your advice, Will work on that

2023-07-31 19:44 UTC, nithindante commented on AmazonAs.java
> +		driver.findElement(By.id("twotabsearchtextbox")).sendKeys(Keys.ARROW_DOWN);
its actually a suggestive drop down,  so instead of going and clicking on the search icon, I thought of manually selecting the second option "frypan" via my keyboard

2023-08-01 13:19 UTC, nithindante commented on AmazonAs.java
> +		Thread.sleep(2000);
yeah, I was not confident on Explict wait and implict wait, I am looking into it right now and will make sure to update the code

2023-08-01 13:19 UTC, nithindante commented on AmazonAs.java
> +				Thread.sleep(2000);
Sure thing

2023-08-01 13:20 UTC, nithindante commented on AmazonAs.java
> +			    driver.findElement(By.xpath("//*[@id=\"address-ui-widgets-form-submit-button\"]/span/input")).click();
Sure, I have created a Assertion which checks whether the text" Select a payment method" is displayed

2023-08-01 13:21 UTC, nithindante commented on AmazonAs.java
> +	public void run() throws InterruptedException
Sure thing, I need to get better with methodnames

2023-08-16 22:37 UTC, merged